<?php
define("PIMIND_HOME", __DIR__);
define("PIMIND_CONFIGS_PATH", PIMIND_HOME.DIRECTORY_SEPARATOR."config");
define("PIMIND_CONFIG", PIMIND_CONFIGS_PATH.DIRECTORY_SEPARATOR."running");
define("PIMIND_STATE", PIMIND_HOME.DIRECTORY_SEPARATOR."state");