<?php
define("PIMIND_HOME", __DIR__);
define("PIMIND_CONFIGS_PATH", PIMIND_HOME.DIRECTORY_SEPARATOR."config");
define("PIMIND_CONFIG", PIMIND_CONFIGS_PATH.DIRECTORY_SEPARATOR."running");
define("PIMIND_STATE", PIMIND_HOME.DIRECTORY_SEPARATOR."state");
define("PIMIND_CONTROLLER", PIMIND_HOME.DIRECTORY_SEPARATOR."controller");
define("PIMIND_CONTROLLER_HANDLERS", PIMIND_CONTROLLER.DIRECTORY_SEPARATOR."handlers");
define("PIMIND_NOTIFIERS", PIMIND_HOME.DIRECTORY_SEPARATOR."notifiers");
define("PIMIND_NOTIFIERS_SOURCE", PIMIND_NOTIFIERS.DIRECTORY_SEPARATOR."src");